# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9090
  servlet:
    context-path: /demo

# Spring
spring:
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Logging
logging:
  path: ./logs/
  file: demo.log
